resource "local_file" "readme" {
  filename = "${var.output_dir}/${var.project_name}-${var.environment}-readme.txt"
  content  = "Project: ${var.project_name} | Env: ${var.environment}"
}

resource "local_file" "config" {
  filename = "${var.output_dir}/${var.project_name}-${var.environment}-config.txt"
  content  = "Auto-generated by Terraform module"
}
